- name: Running Apache
  hosts: azure-web
  become: true
  roles:
    - role: Apache

- name: Run PHP
  hosts: azure-web
  become: true
  roles:
    - role: PHP

- name: Install mysql
  hosts: azure-database
  become: true
  roles:
    - role: mysql

- name: Install Wordpress
  hosts: azure-web
  become: true
  roles:
    - role: WordPress

- name: Create users
  hosts: azure-web, azure-database
  become: true
  roles:
    - role: UserManager

- name: Create groups
  hosts: azure-web, azure-database
  become: true
  roles:
    - role: UserManager

- name: Assign users to groups
  hosts: azure-web, azure-database
  become: true
  roles:
    - role: UserManager

- name: Install MySQL Workbench on Windows Client
  hosts: azure-client
  become: true
  roles:
    - role: MySQLWorkbench