---
# tasks file for WordPress
- name: Wordpress | Check if WordPress is installed
  stat:
    path: "{{ wp_install_dir }}"
  register: wordpress_dir

- name: Wordpress | Remove WordPress if it is installed
  file:
    path: "{{ wp_install_dir }}"
    state: absent
  when: wordpress_dir.stat.exists

- name: "Wordpress | Create app server folder"
  file:
    path: "{{ wp_install_dir }}"
    state: directory
    mode: 0755

- name: "Wordpress | Extract install file"
  unarchive:
    src: "http://wordpress.org/wordpress-6.5.2.tar.gz"
    dest: "{{ wp_install_dir }}"
    remote_src: yes

- name: Wordpress | Move files from {{ wp_install_dir }}/wordpress to {{ wp_install_dir }}
  command: cp -rf . "{{ wp_install_dir }}"
  args:
    chdir: "{{ wp_install_dir }}/wordpress/"

- name: Wordpress | Remove wordpress dir
  file:
    path: "{{ wp_install_dir }}/wordpress/"
    state: absent

- name: Wordpress | Fetch random salts for wp-config.php
  delegate_to: localhost
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  become: False
  register: 'wp_salt_array'

- name: set wp_salt fact
  set_fact:
    wp_salt: '{{ wp_salt_array.content }}'

- name: Wordpress | Copy wp-config.php file
  template:
    src: wp-config.php.j2
    dest: "{{ wp_install_dir }}/wp-config.php"