nodes:
  hosts:
    managed-node:
      ansible_host: 10.0.0.4
      ansible_user: vboxuser
      ansible_ssh_private_key_file: /home/vboxuser/ansible/ssh-keys/ansible-key
    azure-database:
      ansible_host: 10.0.0.132
      ansible_user: vboxuser
      ansible_ssh_private_key_file: /home/vboxuser/ansible/ssh-keys/ansible-key
  