---
# tasks file for mysql
# Ref: https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install MySQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Secure MySQL installation
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create a MySQL database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

- name: Create a MySQL user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present

