---
# tasks file for mysql
- name: Install MySQL
  apt:
    name: mysql-server
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Start up the MySQL service
  shell: "service mysql start"

- name: Ensure MySQL is enabled to run on startup
  service:
    name: mysql
    state: started
    enabled: yes

- name: update mysql root users
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: ""
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Debug MySQL root password
  debug:
    msg: "MySQL root password is {{ mysql_root_password }}"



  
