---
# tasks file for mysql
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Secure MySQL installation
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present

- name: Create a MySQL database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create a MySQL user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

